services:

  nginx-proxy:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - certs:/etc/nginx/certs:ro
   
  docker-gen:
    image: nginxproxy/docker-gen
    container_name: docker-gen
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /etc/docker-gen/templates/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro
      - /etc/nginx/conf.d:/etc/nginx/conf.d
    command: -notify-sighup nginx -watch /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    labels:
      - "com.github.nginx-proxy.docker-gen"

  acme-companion:
    image: nginxproxy/acme-companion
    container_name: nginx-proxy-acme
    environment:
      - DEFAULT_EMAIL=marianogomezb@gmail.com
    volumes_from:
      - nginx-proxy
    volumes:
      - certs:/etc/nginx/certs:rw
      - acme:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro

  draw:
    image: excalidraw/excalidraw:latest
    restart: unless-stopped
    healthcheck:
      disable: true
    environment:
      - VIRTUAL_HOST=draw.magobru.me
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=draw.magobru.me
      - LETSENCRYPT_MAIL=marianogomezb@gmail.com
      - REACT_APP_BACKEND_V1_GET_URL=https://draw.magobru.me/api/v1/
      - REACT_APP_BACKEND_V2_GET_URL=https://draw.magobru.me/api/v2/
      - REACT_APP_BACKEND_V2_POST_URL=https://draw.magobru.me/api/v2/post

volumes:
  conf:
  vhost:
  html:
  certs:
  acme:
